// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjecteV2.ApiSql;

#nullable disable

namespace DBSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240112144718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistaGrup", b =>
                {
                    b.Property<string>("ArtistasNomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GrupsNomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArtistasNomArtista", "GrupsNomGrup");

                    b.HasIndex("GrupsNomGrup");

                    b.ToTable("ArtistaGrup");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nom", "data", "ArtistaNom");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Property<string>("NomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyNaixement")
                        .HasColumnType("int");

                    b.HasKey("NomArtista");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID");

                    b.ToTable("Cançons");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nom");

                    b.ToTable("Extensio");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "Nom");

                    b.HasIndex("Nom");

                    b.HasIndex("UID");

                    b.ToTable("Format");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Grup", b =>
                {
                    b.Property<string>("NomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomGrup");

                    b.ToTable("Grups");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "Nom", "data");

                    b.HasIndex("Nom");

                    b.HasIndex("UID");

                    b.HasIndex("data");

                    b.HasIndex("Nom", "data", "ArtistaNom");

                    b.ToTable("conteAlbum");
                });

            modelBuilder.Entity("ArtistaGrup", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Artista", null)
                        .WithMany()
                        .HasForeignKey("ArtistasNomArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Grup", null)
                        .WithMany()
                        .HasForeignKey("GrupsNomGrup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Extensio", "ExtensioObj")
                        .WithMany("Format")
                        .HasForeignKey("Nom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("Format")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CançoObj");

                    b.Navigation("ExtensioObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Album", "AlbumObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("Nom", "data", "ArtistaNom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumObj");

                    b.Navigation("CançoObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Navigation("conteAlbum");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Navigation("Format");

                    b.Navigation("conteAlbum");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Navigation("Format");
                });
#pragma warning restore 612, 618
        }
    }
}
