// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjecteV2.ApiSql;

#nullable disable

namespace DBSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240109183828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyNaixement")
                        .HasColumnType("int");

                    b.HasKey("Nom");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nom");

                    b.ToTable("Formats");
                });
#pragma warning restore 612, 618
        }
    }
}
