// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjecteV2.ApiSql;

#nullable disable

namespace DBSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240112152004_InitialCreateç")]
    partial class InitialCreateç
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistaGrup", b =>
                {
                    b.Property<string>("artistesNomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("grupsNomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("artistesNomArtista", "grupsNomGrup");

                    b.HasIndex("grupsNomGrup");

                    b.ToTable("ArtistaGrup");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Property<string>("NomAlbum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomAlbum", "data", "ArtistaNom");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Property<string>("NomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyNaixement")
                        .HasColumnType("int");

                    b.HasKey("NomArtista");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID");

                    b.ToTable("Cançons");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.ConteLlista", b =>
                {
                    b.Property<string>("NomLlista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomLlista", "MAC", "UID");

                    b.HasIndex("UID");

                    b.ToTable("ConteLlista");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Property<string>("NomExtensio")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomExtensio");

                    b.ToTable("Extensio");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomFormat")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "NomFormat");

                    b.HasIndex("NomFormat");

                    b.HasIndex("UID");

                    b.ToTable("Format");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Grup", b =>
                {
                    b.Property<string>("NomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomGrup");

                    b.ToTable("Grups");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Instrument", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nom");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Llista", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_MAC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dispositiu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nom", "ID_MAC");

                    b.ToTable("Llista");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Participa", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomCanço")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomInstrument")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "NomCanço", "NomArtista", "NomGrup", "NomInstrument");

                    b.HasIndex("NomArtista");

                    b.HasIndex("NomCanço");

                    b.HasIndex("NomGrup");

                    b.HasIndex("NomInstrument");

                    b.ToTable("Participa");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomAlbum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "NomAlbum", "data");

                    b.HasIndex("NomAlbum");

                    b.HasIndex("UID");

                    b.HasIndex("data");

                    b.HasIndex("NomAlbum", "data", "ArtistaNom");

                    b.ToTable("conteAlbum");
                });

            modelBuilder.Entity("ArtistaGrup", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Artista", null)
                        .WithMany()
                        .HasForeignKey("artistesNomArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Grup", null)
                        .WithMany()
                        .HasForeignKey("grupsNomGrup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.ConteLlista", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Canço", "cançoObj")
                        .WithMany("conteLlista")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Llista", "llistaObj")
                        .WithMany("conteLlista")
                        .HasForeignKey("NomLlista", "MAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cançoObj");

                    b.Navigation("llistaObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Extensio", "ExtensioObj")
                        .WithMany("Format")
                        .HasForeignKey("NomFormat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("Format")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CançoObj");

                    b.Navigation("ExtensioObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Participa", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Artista", "ArtistaObj")
                        .WithMany("participa")
                        .HasForeignKey("NomArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("participa")
                        .HasForeignKey("NomCanço")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Grup", "GrupObj")
                        .WithMany("participa")
                        .HasForeignKey("NomGrup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Instrument", "InstrumentObj")
                        .WithMany("participa")
                        .HasForeignKey("NomInstrument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistaObj");

                    b.Navigation("CançoObj");

                    b.Navigation("GrupObj");

                    b.Navigation("InstrumentObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Album", "AlbumObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("NomAlbum", "data", "ArtistaNom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumObj");

                    b.Navigation("CançoObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Navigation("conteAlbum");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Navigation("participa");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Navigation("Format");

                    b.Navigation("conteAlbum");

                    b.Navigation("conteLlista");

                    b.Navigation("participa");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Navigation("Format");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Grup", b =>
                {
                    b.Navigation("participa");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Instrument", b =>
                {
                    b.Navigation("participa");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Llista", b =>
                {
                    b.Navigation("conteLlista");
                });
#pragma warning restore 612, 618
        }
    }
}
