// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjecteV2.ApiSql;

#nullable disable

namespace DBSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110170900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyNaixement")
                        .HasColumnType("int");

                    b.HasKey("Nom");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID");

                    b.ToTable("Cançons");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Es", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "Nom");

                    b.HasIndex("Nom");

                    b.HasIndex("UID");

                    b.ToTable("es");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nom");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Es", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Format", "FormatObj")
                        .WithMany("Es")
                        .HasForeignKey("Nom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("Es")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CançoObj");

                    b.Navigation("FormatObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Navigation("Es");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Navigation("Es");
                });
#pragma warning restore 612, 618
        }
    }
}
