// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjecteV2.ApiSql;

#nullable disable

namespace DBSql.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Property<string>("NomAlbum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomAlbum", "data", "ArtistaNom");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Property<string>("NomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyNaixement")
                        .HasColumnType("int");

                    b.HasKey("NomArtista");

                    b.ToTable("Artistes");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID");

                    b.ToTable("Cançons");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.ConteLlista", b =>
                {
                    b.Property<string>("NomLlista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomLlista", "MAC", "UID");

                    b.HasIndex("UID");

                    b.ToTable("ConteLlista");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Property<string>("NomExtensio")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomExtensio");

                    b.ToTable("Extensio");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomFormat")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "NomFormat");

                    b.HasIndex("NomFormat");

                    b.HasIndex("UID");

                    b.ToTable("Format");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Grup", b =>
                {
                    b.Property<string>("NomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomGrup");

                    b.ToTable("Grups");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Llista", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_MAC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dispositiu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nom", "ID_MAC");

                    b.ToTable("Llista");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Pertany", b =>
                {
                    b.Property<string>("NomGrup")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomArtista")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataFi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInici")
                        .HasColumnType("datetime2");

                    b.HasKey("NomGrup", "NomArtista");

                    b.HasIndex("NomArtista");

                    b.HasIndex("NomGrup");

                    b.ToTable("Pertany");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomAlbum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistaNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID", "NomAlbum", "data");

                    b.HasIndex("NomAlbum");

                    b.HasIndex("UID");

                    b.HasIndex("data");

                    b.HasIndex("NomAlbum", "data", "ArtistaNom");

                    b.ToTable("conteAlbum");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.ConteLlista", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Canço", "cançoObj")
                        .WithMany("conteLlista")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Llista", "llistaObj")
                        .WithMany("conteLlista")
                        .HasForeignKey("NomLlista", "MAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cançoObj");

                    b.Navigation("llistaObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Format", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Extensio", "ExtensioObj")
                        .WithMany("Format")
                        .HasForeignKey("NomFormat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("Format")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CançoObj");

                    b.Navigation("ExtensioObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Pertany", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Artista", "ArtistaObj")
                        .WithMany("Pertany")
                        .HasForeignKey("NomArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Grup", "GrupObj")
                        .WithMany("Pertany")
                        .HasForeignKey("NomGrup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistaObj");

                    b.Navigation("GrupObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.conteAlbum", b =>
                {
                    b.HasOne("ProjecteV2.ApiSql.Canço", "CançoObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjecteV2.ApiSql.Album", "AlbumObj")
                        .WithMany("conteAlbum")
                        .HasForeignKey("NomAlbum", "data", "ArtistaNom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumObj");

                    b.Navigation("CançoObj");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Album", b =>
                {
                    b.Navigation("conteAlbum");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Artista", b =>
                {
                    b.Navigation("Pertany");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Canço", b =>
                {
                    b.Navigation("Format");

                    b.Navigation("conteAlbum");

                    b.Navigation("conteLlista");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Extensio", b =>
                {
                    b.Navigation("Format");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Grup", b =>
                {
                    b.Navigation("Pertany");
                });

            modelBuilder.Entity("ProjecteV2.ApiSql.Llista", b =>
                {
                    b.Navigation("conteLlista");
                });
#pragma warning restore 612, 618
        }
    }
}
